---
id: Stringprep
name: Internationalized strings preparation library
full: >
  PHP implementation of RFC 3454 - Preparation of Internationalized Strings ("stringprep").
description: Horde wrapper around the znerol/php-stringprep package.
list: dev
type: library
