---
id: Stringprep
name: Stringprep
full: Internationalized strings preparation library
description: |-
  PHP implementation library of RFC 3454 - Preparation of Internationalized Strings ("stringprep").
  A wrapper around the znerol/php-stringprep package.
list: dev
type: library
authors:
  -
    name: Michael Slusarz
    user: slusarz
    email: slusarz@horde.org
    active: false
    role: lead
version:
  release: 2.0.0alpha1
  api: 2.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: LGPL-3.0
  uri: http://opensource.org/licenses/lgpl-3.0.html
dependencies:
  required:
    php: ^5.3 || ^7
    ext:
      iconv: '*'
      intl: '*'
